# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/houdonghui/cm3_ahbmtx_mcu/project/fpga_syn/fpga_ku6_mcu_full_vivado/fpga_ku6_mcu_full_pin_assignments.xdc

# XDC: /home/houdonghui/cm3_ahbmtx_mcu/project/fpga_syn/fpga_ku6_mcu_full_vivado/fpga_ku6_mcu_full_timing_constrain.xdc

# IP: /home/houdonghui/cm3_ahbmtx_mcu/library/xilinx_ip/pll_50m/pll_50m.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pll_50m || ORIG_REF_NAME==pll_50m} -quiet] -quiet

# IP: /home/houdonghui/cm3_ahbmtx_mcu/library/xilinx_ip/ram_128k/ram_128k.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_128k || ORIG_REF_NAME==ram_128k} -quiet] -quiet
