set_property MARK_DEBUG false [get_nets {u_fp_domain/u_apb3_caliptra_sync/qspi_data_device_to_host[2]}]
set_property MARK_DEBUG false [get_nets {u_fp_domain/u_apb3_caliptra_sync/qspi_data_device_to_host[3]}]
set_property MARK_DEBUG false [get_nets {u_fp_domain/u_apb3_caliptra_sync/qspi_data_host_to_device[2]}]
set_property MARK_DEBUG false [get_nets {u_fp_domain/u_apb3_caliptra_sync/qspi_data_host_to_device[3]}]
set_property MARK_DEBUG false [get_nets {u_fp_domain/u_apb3_caliptra_sync/qspi_data_host_to_device_en[3]}]
set_property MARK_DEBUG false [get_nets {u_fp_domain/u_apb3_caliptra_sync/qspi_data_host_to_device_en[2]}]
set_property MARK_DEBUG false [get_nets u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/n_1_0]
set_property MARK_DEBUG false [get_nets u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/n_1_1]
set_property MARK_DEBUG false [get_nets u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/n_1_2]
set_property MARK_DEBUG false [get_nets u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/n_1_3]
set_property MARK_DEBUG false [get_nets u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/n_1_4]
set_property MARK_DEBUG false [get_nets u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/n_1_5]
set_property MARK_DEBUG false [get_nets u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/n_1_6]
set_property MARK_DEBUG false [get_nets u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/n_1_7]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/clk_cg_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 64 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[0]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[1]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[2]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[3]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[4]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[5]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[6]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[7]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[8]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[9]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[10]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[11]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[12]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[13]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[14]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[15]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[16]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[17]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[18]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[19]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[20]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[21]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[22]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[23]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[24]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[25]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[26]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[27]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[28]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[29]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[30]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[31]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[32]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[33]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[34]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[35]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[36]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[37]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[38]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[39]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[40]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[41]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[42]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[43]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[44]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[45]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[46]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[47]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[48]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[49]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[50]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[51]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[52]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[53]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[54]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[55]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[56]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[57]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[58]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[59]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[60]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[61]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[62]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwdata[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_htrans[0]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_htrans[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hsize[0]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hsize[1]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hsize[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 64 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[0]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[1]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[2]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[3]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[4]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[5]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[6]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[7]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[8]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[9]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[10]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[11]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[12]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[13]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[14]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[15]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[16]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[17]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[18]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[19]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[20]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[21]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[22]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[23]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[24]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[25]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[26]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[27]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[28]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[29]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[30]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[31]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[32]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[33]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[34]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[35]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[36]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[37]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[38]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[39]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[40]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[41]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[42]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[43]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[44]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[45]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[46]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[47]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[48]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[49]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[50]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[51]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[52]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[53]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[54]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[55]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[56]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[57]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[58]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[59]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[60]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[61]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[62]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hrdata[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[0]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[1]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[2]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[3]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[4]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[5]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[6]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[7]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[8]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[9]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[10]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[11]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[12]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[13]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[14]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[15]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[16]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[17]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[18]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[19]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[20]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[21]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[22]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[23]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[24]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[25]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[26]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[27]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[28]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[29]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[30]} {u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_haddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/ca_qspi_cs[0]} {u_fp_domain/u_apb3_caliptra_sync/ca_qspi_cs[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/qspi_data_device_to_host[0]} {u_fp_domain/u_apb3_caliptra_sync/qspi_data_device_to_host[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/qspi_data_host_to_device[0]} {u_fp_domain/u_apb3_caliptra_sync/qspi_data_host_to_device[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 2 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/qspi_data_host_to_device_en[0]} {u_fp_domain/u_apb3_caliptra_sync/qspi_data_host_to_device_en[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list u_fp_domain/u_apb3_caliptra_sync/ca_qspi_clk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list u_fp_domain/u_apb3_caliptra_sync/caliptra_top_dut/rvtop/lsu_hwrite]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list u_fpga_platform/u_pll0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 4 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/itrng_data[0]} {u_fp_domain/u_apb3_caliptra_sync/itrng_data[1]} {u_fp_domain/u_apb3_caliptra_sync/itrng_data[2]} {u_fp_domain/u_apb3_caliptra_sync/itrng_data[3]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 30 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {u_fp_domain/u_apb3_caliptra_sync/paddr[2]} {u_fp_domain/u_apb3_caliptra_sync/paddr[3]} {u_fp_domain/u_apb3_caliptra_sync/paddr[4]} {u_fp_domain/u_apb3_caliptra_sync/paddr[5]} {u_fp_domain/u_apb3_caliptra_sync/paddr[6]} {u_fp_domain/u_apb3_caliptra_sync/paddr[7]} {u_fp_domain/u_apb3_caliptra_sync/paddr[8]} {u_fp_domain/u_apb3_caliptra_sync/paddr[9]} {u_fp_domain/u_apb3_caliptra_sync/paddr[10]} {u_fp_domain/u_apb3_caliptra_sync/paddr[11]} {u_fp_domain/u_apb3_caliptra_sync/paddr[12]} {u_fp_domain/u_apb3_caliptra_sync/paddr[13]} {u_fp_domain/u_apb3_caliptra_sync/paddr[14]} {u_fp_domain/u_apb3_caliptra_sync/paddr[15]} {u_fp_domain/u_apb3_caliptra_sync/paddr[16]} {u_fp_domain/u_apb3_caliptra_sync/paddr[17]} {u_fp_domain/u_apb3_caliptra_sync/paddr[18]} {u_fp_domain/u_apb3_caliptra_sync/paddr[19]} {u_fp_domain/u_apb3_caliptra_sync/paddr[20]} {u_fp_domain/u_apb3_caliptra_sync/paddr[21]} {u_fp_domain/u_apb3_caliptra_sync/paddr[22]} {u_fp_domain/u_apb3_caliptra_sync/paddr[23]} {u_fp_domain/u_apb3_caliptra_sync/paddr[24]} {u_fp_domain/u_apb3_caliptra_sync/paddr[25]} {u_fp_domain/u_apb3_caliptra_sync/paddr[26]} {u_fp_domain/u_apb3_caliptra_sync/paddr[27]} {u_fp_domain/u_apb3_caliptra_sync/paddr[28]} {u_fp_domain/u_apb3_caliptra_sync/paddr[29]} {u_fp_domain/u_apb3_caliptra_sync/paddr[30]} {u_fp_domain/u_apb3_caliptra_sync/paddr[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list u_fp_domain/u_apb3_caliptra_sync/etrng_req]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list u_fp_domain/u_apb3_caliptra_sync/itrng_valid]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list u_fp_domain/u_apb3_caliptra_sync/n_1_0]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list u_fp_domain/u_apb3_caliptra_sync/n_1_1]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets hsi]
