// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ClockSinkDomain_2(	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
  input         auto_in_psel,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_penable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_pwrite,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [29:0] auto_in_paddr,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_in_pwdata,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_in_pstrb,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_pready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_in_prdata,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire             in_valid;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:48:26]
  wire [3:0]       in_bits_mask;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:46:25]
  wire             in_bits_read;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:43:22]
  wire             _out_wofireMux_T_2;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24]
  wire             _out_wofireMux_T;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24]
  wire             out_backSel_3;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24]
  wire             out_backSel_2;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24]
  wire             _impl_io_impl_input_ready;	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:214:26]
  wire             _impl_io_impl_output_valid;	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:214:26]
  wire [31:0]      _impl_io_impl_gcd;	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:214:26]
  reg  [31:0]      x;	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:208:18]
  wire             _out_T_7 = auto_in_paddr[17:4] == 14'h0;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24, :44:{19,32}]
  wire [31:0]      out_backMask = {{8{in_bits_mask[3]}}, {8{in_bits_mask[2]}}, {8{in_bits_mask[1]}}, {8{in_bits_mask[0]}}};	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24, :46:25]
  assign out_backSel_2 = auto_in_paddr[3:2] == 2'h2;	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9, generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24]
  assign out_backSel_3 = &(auto_in_paddr[3:2]);	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24]
  assign _out_wofireMux_T = in_valid & auto_in_penable;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24, :48:26]
  wire [3:0]       _GEN = {{|{_impl_io_impl_output_valid | ~(|out_backMask), auto_in_paddr[17:4]}}, {1'h1}, {1'h1}, {1'h1}};	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9, :214:26, generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24, :44:{19,32}, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  assign _out_wofireMux_T_2 = _out_wofireMux_T & auto_in_pwrite;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24]
  wire [3:0]       _GEN_0 = {{1'h1}, {|{_impl_io_impl_input_ready | ~(&out_backMask), auto_in_paddr[17:4]}}, {1'h1}, {1'h1}};	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9, :214:26, generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24, :44:{19,32}, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  wire             out_oready = auto_in_pwrite ? _GEN_0[auto_in_paddr[3:2]] : _GEN[auto_in_paddr[3:2]];	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  wire             out_valid = in_valid & out_oready;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24, :48:26]
  wire [3:0][31:0] _GEN_1 = {{_impl_io_impl_gcd}, {32'h0}, {32'h0}, {{30'h0, _impl_io_impl_input_ready, _impl_io_impl_output_valid}}};	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:214:26, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:{10,48}]
  reg              taken;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:39:24]
  assign in_bits_read = ~auto_in_pwrite;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:43:22]
  assign in_bits_mask = auto_in_pwrite ? auto_in_pstrb : 4'hF;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:46:25]
  assign in_valid = auto_in_psel & ~taken;	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:39:24, :48:{26,29}]
  always @(posedge auto_clock_in_clock) begin	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
    if (_out_wofireMux_T_2 & auto_in_paddr[3:2] == 2'h1 & _out_T_7 & (&out_backMask))	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9, generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24]
      x <= auto_in_pwdata;	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:208:18]
    if (auto_clock_in_reset)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
      taken <= 1'h0;	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9, generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:39:24]
    else	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
      taken <= ~(auto_in_penable & out_valid) & (auto_in_penable & out_oready & in_valid | taken);	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24, :39:24, :40:{21,29}, :41:{21,29}, :48:26, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
    initial begin	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
        `INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
        end	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
        x = _RANDOM[1'h0];	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9, :208:18]
        taken = _RANDOM[1'h1][0];	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9, generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:39:24]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  GCDAPBMMIOBlackBox #(
    .WIDTH(32)
  ) impl_io_impl (	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:214:26]
    .clock        (auto_clock_in_clock),
    .reset        (auto_clock_in_reset),
    .input_ready  (_impl_io_impl_input_ready),
    .input_valid  (_out_wofireMux_T_2 & out_backSel_2 & _out_T_7 & (&out_backMask)),	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24]
    .x            (x),	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:208:18]
    .y            (auto_in_pwdata),
    .output_ready (_out_wofireMux_T & in_bits_read & out_backSel_3 & _out_T_7 & (|out_backMask)),	// @[generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24, :43:22]
    .output_valid (_impl_io_impl_output_valid),
    .gcd          (_impl_io_impl_gcd),
    .busy         (/* unused */)
  );	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:214:26]
  assign auto_in_pready = out_valid;	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9, generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24]
  assign auto_in_prdata = _out_T_7 ? _GEN_1[auto_in_paddr[3:2]] : 32'h0;	// @[generators/chipyard/src/main/scala/example/GCDAPB.scala:204:9, generators/rocket-chip/src/main/scala/amba/apb/RegisterRouter.scala:36:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
endmodule

