// Generated by CIRCT firtool-1.75.0
module DCacheDataArray(	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7]
  input         io_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [11:0] io_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input         io_req_bits_write,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [63:0] io_req_bits_wdata,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [7:0]  io_req_bits_eccMask,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [3:0]  io_req_bits_way_en,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  output [63:0] io_resp_0,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  output [63:0] io_resp_1,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  output [63:0] io_resp_2,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  output [63:0] io_resp_3	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
);

  wire         rockettile_dcache_data_arrays_0_rdata_data_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:77:39]
  wire         rockettile_dcache_data_arrays_0_rdata_MPORT_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17]
  wire [255:0] _rockettile_dcache_data_arrays_0_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  assign rockettile_dcache_data_arrays_0_rdata_MPORT_en = io_req_valid & io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17]
  assign rockettile_dcache_data_arrays_0_rdata_data_en = io_req_valid & ~io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:77:{39,42}]
  rockettile_dcache_data_arrays_0 rockettile_dcache_data_arrays_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (io_req_bits_addr[11:3]),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:59:31]
    .RW0_en    (rockettile_dcache_data_arrays_0_rdata_data_en | rockettile_dcache_data_arrays_0_rdata_MPORT_en),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17, :77:39, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({4{io_req_bits_wdata}}),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_rockettile_dcache_data_arrays_0_RW0_rdata),
    .RW0_wmask ({io_req_bits_eccMask[7] & io_req_bits_way_en[3], io_req_bits_eccMask[6] & io_req_bits_way_en[3], io_req_bits_eccMask[5] & io_req_bits_way_en[3], io_req_bits_eccMask[4] & io_req_bits_way_en[3], io_req_bits_eccMask[3] & io_req_bits_way_en[3], io_req_bits_eccMask[2] & io_req_bits_way_en[3], io_req_bits_eccMask[1] & io_req_bits_way_en[3], io_req_bits_eccMask[0] & io_req_bits_way_en[3], io_req_bits_eccMask[7] & io_req_bits_way_en[2], io_req_bits_eccMask[6] & io_req_bits_way_en[2], io_req_bits_eccMask[5] & io_req_bits_way_en[2], io_req_bits_eccMask[4] & io_req_bits_way_en[2], io_req_bits_eccMask[3] & io_req_bits_way_en[2], io_req_bits_eccMask[2] & io_req_bits_way_en[2], io_req_bits_eccMask[1] & io_req_bits_way_en[2], io_req_bits_eccMask[0] & io_req_bits_way_en[2], io_req_bits_eccMask[7] & io_req_bits_way_en[1], io_req_bits_eccMask[6] & io_req_bits_way_en[1], io_req_bits_eccMask[5] & io_req_bits_way_en[1], io_req_bits_eccMask[4] & io_req_bits_way_en[1], io_req_bits_eccMask[3] & io_req_bits_way_en[1], io_req_bits_eccMask[2] & io_req_bits_way_en[1], io_req_bits_eccMask[1] & io_req_bits_way_en[1], io_req_bits_eccMask[0] & io_req_bits_way_en[1], io_req_bits_eccMask[7] & io_req_bits_way_en[0], io_req_bits_eccMask[6] & io_req_bits_way_en[0], io_req_bits_eccMask[5] & io_req_bits_way_en[0], io_req_bits_eccMask[4] & io_req_bits_way_en[0], io_req_bits_eccMask[3] & io_req_bits_way_en[0], io_req_bits_eccMask[2] & io_req_bits_way_en[0], io_req_bits_eccMask[1] & io_req_bits_way_en[0], io_req_bits_eccMask[0] & io_req_bits_way_en[0]})	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:56:82, :57:{87,108}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  assign io_resp_0 = _rockettile_dcache_data_arrays_0_RW0_rdata[63:0];	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:45:27]
  assign io_resp_1 = _rockettile_dcache_data_arrays_0_RW0_rdata[127:64];	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:45:27]
  assign io_resp_2 = _rockettile_dcache_data_arrays_0_RW0_rdata[191:128];	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:45:27]
  assign io_resp_3 = _rockettile_dcache_data_arrays_0_RW0_rdata[255:192];	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:45:27]
endmodule

