`include "config_defines.svh"
// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module KU060FPGATestHarness(	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
   input                       ca_jtag_tck,    // JTAG clk
    input                       ca_jtag_tms,    // JTAG TMS
    input                       ca_jtag_tdi,    // JTAG tdi
    input                       ca_jtag_trst_n, // JTAG Reset
    output                      ca_jtag_tdo,    // JTAG TDO

    //QSPI Interface
    output logic                                ca_qspi_clk,
    output logic                                ca_qspi_cs,
    inout wire [`CALIPTRA_QSPI_IO_WIDTH-1:0]    ca_qspi_data,
    //uart export
    output                                 ca_uart_tx,
    input                                  ca_uart_rx,

    input   [2:0]               security_state,
    input                       scan_mode,
    
    
  input         sys_clock_p,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  input         sys_clock_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout         uart_txd,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout         uart_rxd,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
//  inout         uart_rtsn,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
//  inout         uart_ctsn,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
//  inout         sdio_spi_clk,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
//  inout         sdio_spi_cs,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
//  inout         sdio_spi_dat_0,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
//  inout         sdio_spi_dat_1,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
//  inout         sdio_spi_dat_2,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
//  inout         sdio_spi_dat_3,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output [16:0] ddr_c0_ddr4_adr,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_c0_ddr4_bg,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output [1:0]  ddr_c0_ddr4_ba,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_c0_ddr4_reset_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_c0_ddr4_act_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_c0_ddr4_ck_c,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_c0_ddr4_ck_t,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_c0_ddr4_cke,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_c0_ddr4_cs_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_c0_ddr4_odt,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout  [63:0] ddr_c0_ddr4_dq,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout  [7:0]  ddr_c0_ddr4_dqs_c,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout  [7:0]  ddr_c0_ddr4_dqs_t,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout  [7:0]  ddr_c0_ddr4_dm_dbi_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout         jtag_jtag_TCK,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout         jtag_jtag_TMS,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout         jtag_jtag_TDI,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout         jtag_jtag_TDO,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout         jtag_srst_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  input         reset_0	// @[fpga/src/main/scala/ku060/TestHarness.scala:100:17]
);

  wire        reset = ~reset_0;  
  wire        harnessSysPLLIn_reset;	// @[fpga/src/main/scala/ku060/TestHarness.scala:115:38]
  wire        _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire        _chiptop0_uart_0_txd;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_tl_slave_0_a_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_opcode;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_param;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_tl_slave_0_a_bits_source;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [31:0] _chiptop0_tl_slave_0_a_bits_address;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_tl_slave_0_a_bits_mask;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [63:0] _chiptop0_tl_slave_0_a_bits_data;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_tl_slave_0_a_bits_corrupt;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_tl_slave_0_d_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_spi_0_sck;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_spi_0_dq_0_o;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_spi_0_cs_0;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_jtag_TDO;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _fpga_power_on_power_on_reset;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
  wire        _IBUF_O;	// @[fpga/src/main/scala/ku060/TestHarness.scala:102:25]
  wire        _jtagDebugSourceIn_TDI_a2b_b;	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  wire        _jtagDebugSourceIn_TMS_a2b_b;	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  wire        _jtagDebugSourceIn_TCK_a2b_b;	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  wire        _a2b_4_b;	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  wire        _io_uart_bbIn_rxd_a2b_b;	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  wire        _sys_clock_ibufds_O;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:14:24]
  wire        _harnessSysPLL_clk_out1;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:84:55]
  wire        _harnessSysPLL_locked;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:84:55]
  wire        _mig_auto_buffer_in_a_ready;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire        _mig_auto_buffer_in_d_valid;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire [2:0]  _mig_auto_buffer_in_d_bits_opcode;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire [1:0]  _mig_auto_buffer_in_d_bits_param;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire [3:0]  _mig_auto_buffer_in_d_bits_size;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire [3:0]  _mig_auto_buffer_in_d_bits_source;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire        _mig_auto_buffer_in_d_bits_sink;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire        _mig_auto_buffer_in_d_bits_denied;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire [63:0] _mig_auto_buffer_in_d_bits_data;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire        _mig_auto_buffer_in_d_bits_corrupt;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire        _mig_io_port_c0_ddr4_ui_clk;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire        _mig_io_port_c0_ddr4_ui_clk_sync_rst;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  wire        _dutWrangler_auto_out_1_reset;	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
  wire        _dutWrangler_auto_out_0_clock;	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
  wire        _dutWrangler_auto_out_0_reset;	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
  reg         io_spi_bbIn_dq_1_i_REG;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/SDIOOverlay.scala:18:39]
  reg         io_spi_bbIn_dq_1_i_REG_1;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/SDIOOverlay.scala:18:31]
  assign harnessSysPLLIn_reset = _IBUF_O | _fpga_power_on_power_on_reset;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21, fpga/src/main/scala/ku060/TestHarness.scala:102:25, :115:38]
  always @(posedge _dutWrangler_auto_out_0_clock) begin	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
    io_spi_bbIn_dq_1_i_REG <= _a2b_4_b;	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21, fpga/fpga-shells/src/main/scala/shell/xilinx/SDIOOverlay.scala:18:39]
    io_spi_bbIn_dq_1_i_REG_1 <= io_spi_bbIn_dq_1_i_REG;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/SDIOOverlay.scala:18:{31,39}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
    initial begin	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
        `INIT_RANDOM_PROLOG_	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
        io_spi_bbIn_dq_1_i_REG = _RANDOM[/*Zero width*/ 1'b0][2];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/SDIOOverlay.scala:18:39, generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
        io_spi_bbIn_dq_1_i_REG_1 = _RANDOM[/*Zero width*/ 1'b0][3];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/SDIOOverlay.scala:18:{31,39}, generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetWrangler dutWrangler (	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
    .auto_in_1_clock  (_mig_io_port_c0_ddr4_ui_clk),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .auto_in_1_reset  (_mig_io_port_c0_ddr4_ui_clk_sync_rst),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .auto_in_0_clock  (_harnessSysPLL_clk_out1),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:84:55]
    .auto_in_0_reset  (~_harnessSysPLL_locked | harnessSysPLLIn_reset),	// @[fpga/fpga-shells/src/main/scala/clocks/PLLFactory.scala:78:{20,35}, fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:84:55, fpga/src/main/scala/ku060/TestHarness.scala:115:38]
    .auto_out_1_reset (_dutWrangler_auto_out_1_reset),
    .auto_out_0_clock (_dutWrangler_auto_out_0_clock),
    .auto_out_0_reset (_dutWrangler_auto_out_0_reset)
  );	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
  XilinxVCU118MIG mig (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .clock                           (_dutWrangler_auto_out_0_clock),	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
    .reset                           (_dutWrangler_auto_out_0_reset),	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
    .auto_buffer_in_a_ready          (_mig_auto_buffer_in_a_ready),
    .auto_buffer_in_a_valid          (_chiptop0_tl_slave_0_a_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_opcode    (_chiptop0_tl_slave_0_a_bits_opcode),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_param     (_chiptop0_tl_slave_0_a_bits_param),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_size      ({1'h0, _chiptop0_tl_slave_0_a_bits_size}),	// @[fpga/src/main/scala/ku060/HarnessBinders.scala:36:21, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40, generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
    .auto_buffer_in_a_bits_source    (_chiptop0_tl_slave_0_a_bits_source),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_address   (_chiptop0_tl_slave_0_a_bits_address),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_mask      (_chiptop0_tl_slave_0_a_bits_mask),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_data      (_chiptop0_tl_slave_0_a_bits_data),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_corrupt   (_chiptop0_tl_slave_0_a_bits_corrupt),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_d_ready          (_chiptop0_tl_slave_0_d_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_d_valid          (_mig_auto_buffer_in_d_valid),
    .auto_buffer_in_d_bits_opcode    (_mig_auto_buffer_in_d_bits_opcode),
    .auto_buffer_in_d_bits_param     (_mig_auto_buffer_in_d_bits_param),
    .auto_buffer_in_d_bits_size      (_mig_auto_buffer_in_d_bits_size),
    .auto_buffer_in_d_bits_source    (_mig_auto_buffer_in_d_bits_source),
    .auto_buffer_in_d_bits_sink      (_mig_auto_buffer_in_d_bits_sink),
    .auto_buffer_in_d_bits_denied    (_mig_auto_buffer_in_d_bits_denied),
    .auto_buffer_in_d_bits_data      (_mig_auto_buffer_in_d_bits_data),
    .auto_buffer_in_d_bits_corrupt   (_mig_auto_buffer_in_d_bits_corrupt),
    .io_port_c0_ddr4_adr             (ddr_c0_ddr4_adr),
    .io_port_c0_ddr4_bg              (ddr_c0_ddr4_bg),
    .io_port_c0_ddr4_ba              (ddr_c0_ddr4_ba),
    .io_port_c0_ddr4_reset_n         (ddr_c0_ddr4_reset_n),
    .io_port_c0_ddr4_act_n           (ddr_c0_ddr4_act_n),
    .io_port_c0_ddr4_ck_c            (ddr_c0_ddr4_ck_c),
    .io_port_c0_ddr4_ck_t            (ddr_c0_ddr4_ck_t),
    .io_port_c0_ddr4_cke             (ddr_c0_ddr4_cke),
    .io_port_c0_ddr4_cs_n            (ddr_c0_ddr4_cs_n),
    .io_port_c0_ddr4_odt             (ddr_c0_ddr4_odt),
    .io_port_c0_ddr4_dq              (ddr_c0_ddr4_dq),
    .io_port_c0_ddr4_dqs_c           (ddr_c0_ddr4_dqs_c),
    .io_port_c0_ddr4_dqs_t           (ddr_c0_ddr4_dqs_t),
    .io_port_c0_ddr4_dm_dbi_n        (ddr_c0_ddr4_dm_dbi_n),
    .io_port_c0_sys_clk_i            (_sys_clock_ibufds_O),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:14:24]
    .io_port_c0_ddr4_ui_clk          (_mig_io_port_c0_ddr4_ui_clk),
    .io_port_c0_ddr4_ui_clk_sync_rst (_mig_io_port_c0_ddr4_ui_clk_sync_rst),
    .io_port_c0_ddr4_aresetn         (~_dutWrangler_auto_out_1_reset),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:331:29, fpga/src/main/scala/ku060/TestHarness.scala:55:31]
    .io_port_sys_rst                 (harnessSysPLLIn_reset)	// @[fpga/src/main/scala/ku060/TestHarness.scala:115:38]
  );	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
  harnessSysPLL harnessSysPLL (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:84:55]
    .clk_in1  (_sys_clock_ibufds_O),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:14:24]
    .clk_out1 (_harnessSysPLL_clk_out1),
    .reset    (harnessSysPLLIn_reset),	// @[fpga/src/main/scala/ku060/TestHarness.scala:115:38]
    .locked   (_harnessSysPLL_locked)
  );	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:84:55]
  IBUFDS #(
    .CAPACITANCE("DONT_CARE"),
    .DIFF_TERM("FALSE"),
    .DQS_BIAS("FALSE"),
    .IBUF_DELAY_VALUE(0),
    .IBUF_LOW_PWR("TRUE"),
    .IFD_DELAY_VALUE("AUTO"),
    .IOSTANDARD("DEFAULT")
  ) sys_clock_ibufds (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:14:24]
    .O  (_sys_clock_ibufds_O),
    .I  (sys_clock_p),
    .IB (sys_clock_n)
  );	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:14:24]
  UIntToAnalog_1 a2b (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
    .a    (uart_txd),
    .b    (_chiptop0_uart_0_txd),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .b_en (1'h1)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
  AnalogToUInt_1 io_uart_bbIn_rxd_a2b (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .a (uart_rxd),
    .b (_io_uart_bbIn_rxd_a2b_b)
  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
//  UIntToAnalog_1 a2b_1 (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
//    .a    (sdio_spi_clk),
//    .b    (_chiptop0_spi_0_sck),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
//    .b_en (1'h1)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
//  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
//  UIntToAnalog_1 a2b_2 (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
//    .a    (sdio_spi_dat_3),
//    .b    (_chiptop0_spi_0_cs_0),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
//    .b_en (1'h1)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
//  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
//  UIntToAnalog_1 a2b_3 (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
//    .a    (sdio_spi_cs),
//    .b    (_chiptop0_spi_0_dq_0_o),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
//    .b_en (1'h1)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
//  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
//  AnalogToUInt_1 a2b_4 (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
//    .a (sdio_spi_dat_0),
//    .b (_a2b_4_b)
//  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  AnalogToUInt_1 jtagDebugSourceIn_TCK_a2b (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .a (jtag_jtag_TCK),
    .b (_jtagDebugSourceIn_TCK_a2b_b)
  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  AnalogToUInt_1 jtagDebugSourceIn_TMS_a2b (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .a (jtag_jtag_TMS),
    .b (_jtagDebugSourceIn_TMS_a2b_b)
  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  AnalogToUInt_1 jtagDebugSourceIn_TDI_a2b (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .a (jtag_jtag_TDI),
    .b (_jtagDebugSourceIn_TDI_a2b_b)
  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  UIntToAnalog_1 a2b_5 (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
    .a    (jtag_jtag_TDO),
    .b    (_chiptop0_jtag_TDO),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .b_en (1'h1)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
  AnalogToUInt_1 jtagDebugSourceIn_srst_n_a2b (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .a (jtag_srst_n),
    .b (/* unused */)
  );	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  IBUF IBUF (	// @[fpga/src/main/scala/ku060/TestHarness.scala:102:25]
    .O (_IBUF_O),
    .I (reset)
  );	// @[fpga/src/main/scala/ku060/TestHarness.scala:102:25]
  PowerOnResetFPGAOnly fpga_power_on (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
    .clock          (_sys_clock_ibufds_O),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:14:24]
    .power_on_reset (_fpga_power_on_power_on_reset)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
  ChipTop chiptop0 (	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .ca_jtag_tck(ca_jtag_tck),
    .ca_jtag_tms(ca_jtag_tms),
    .ca_jtag_tdi(ca_jtag_tdi),
    .ca_jtag_trst_n(ca_jtag_trst_n),
    .ca_jtag_tdo(ca_jtag_tdo),
    .ca_qspi_clk(ca_qspi_clk),
    .ca_qspi_cs(ca_qspi_cs),
    .ca_qspi_data(ca_qspi_data),
    .ca_uart_tx(ca_uart_tx),
    .ca_uart_rx(ca_uart_rx),
    .security_state(security_state),
    .scan_mode(scan_mode),
    .uart_0_txd                (_chiptop0_uart_0_txd),
    .uart_0_rxd                (_io_uart_bbIn_rxd_a2b_b),	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .tl_slave_0_a_ready        (_mig_auto_buffer_in_a_ready),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .tl_slave_0_a_valid        (_chiptop0_tl_slave_0_a_valid),
    .tl_slave_0_a_bits_opcode  (_chiptop0_tl_slave_0_a_bits_opcode),
    .tl_slave_0_a_bits_param   (_chiptop0_tl_slave_0_a_bits_param),
    .tl_slave_0_a_bits_size    (_chiptop0_tl_slave_0_a_bits_size),
    .tl_slave_0_a_bits_source  (_chiptop0_tl_slave_0_a_bits_source),
    .tl_slave_0_a_bits_address (_chiptop0_tl_slave_0_a_bits_address),
    .tl_slave_0_a_bits_mask    (_chiptop0_tl_slave_0_a_bits_mask),
    .tl_slave_0_a_bits_data    (_chiptop0_tl_slave_0_a_bits_data),
    .tl_slave_0_a_bits_corrupt (_chiptop0_tl_slave_0_a_bits_corrupt),
    .tl_slave_0_d_ready        (_chiptop0_tl_slave_0_d_ready),
    .tl_slave_0_d_valid        (_mig_auto_buffer_in_d_valid),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .tl_slave_0_d_bits_opcode  (_mig_auto_buffer_in_d_bits_opcode),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .tl_slave_0_d_bits_param   (_mig_auto_buffer_in_d_bits_param),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .tl_slave_0_d_bits_size    (_mig_auto_buffer_in_d_bits_size[2:0]),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23, fpga/src/main/scala/ku060/HarnessBinders.scala:36:21]
    .tl_slave_0_d_bits_source  (_mig_auto_buffer_in_d_bits_source),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .tl_slave_0_d_bits_sink    (_mig_auto_buffer_in_d_bits_sink),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .tl_slave_0_d_bits_denied  (_mig_auto_buffer_in_d_bits_denied),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .tl_slave_0_d_bits_data    (_mig_auto_buffer_in_d_bits_data),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .tl_slave_0_d_bits_corrupt (_mig_auto_buffer_in_d_bits_corrupt),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/VCU118NewShell.scala:312:23]
    .spi_0_sck                 (_chiptop0_spi_0_sck),
    .spi_0_dq_0_i              (1'h0),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
    .spi_0_dq_0_o              (_chiptop0_spi_0_dq_0_o),
    .spi_0_dq_0_ie             (/* unused */),
    .spi_0_dq_0_oe             (/* unused */),
    .spi_0_dq_1_i              (io_spi_bbIn_dq_1_i_REG_1),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/SDIOOverlay.scala:18:31]
    .spi_0_dq_1_o              (/* unused */),
    .spi_0_dq_1_ie             (/* unused */),
    .spi_0_dq_1_oe             (/* unused */),
    .spi_0_dq_2_i              (1'h0),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
    .spi_0_dq_2_o              (/* unused */),
    .spi_0_dq_2_ie             (/* unused */),
    .spi_0_dq_2_oe             (/* unused */),
    .spi_0_dq_3_i              (1'h0),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:149:7]
    .spi_0_dq_3_o              (/* unused */),
    .spi_0_dq_3_ie             (/* unused */),
    .spi_0_dq_3_oe             (/* unused */),
    .spi_0_cs_0                (_chiptop0_spi_0_cs_0),
    .custom_boot               (_plusarg_reader_out),	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .jtag_TCK                  (_jtagDebugSourceIn_TCK_a2b_b),	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .jtag_TMS                  (_jtagDebugSourceIn_TMS_a2b_b),	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .jtag_TDI                  (_jtagDebugSourceIn_TDI_a2b_b),	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .jtag_TDO                  (_chiptop0_jtag_TDO),
    .reset_io                  (_dutWrangler_auto_out_0_reset),	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
    .clock_uncore              (_dutWrangler_auto_out_0_clock),	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
    .clock_tap                 (/* unused */)
  );	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("custom_boot_pin=%d"),
    .WIDTH(1)
  ) plusarg_reader (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  ResetCatchAndSync_d3 harnessBinderReset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (_dutWrangler_auto_out_0_clock),	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
    .reset         (_dutWrangler_auto_out_0_reset),	// @[fpga/src/main/scala/ku060/TestHarness.scala:55:31]
    .io_sync_reset (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
endmodule
