// Generated by CIRCT firtool-1.75.0
module TLInterconnectCoupler_pbus_to_gcd(	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:138:7]
  input         clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:138:7]
  input         reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:138:7]
  output        auto_tl2apb_out_psel,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl2apb_out_penable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl2apb_out_pwrite,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [29:0] auto_tl2apb_out_paddr,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_tl2apb_out_pwdata,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_tl2apb_out_pstrb,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl2apb_out_pready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_tl2apb_out_prdata,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_tl_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_tl_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_tl_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_tl_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [29:0] auto_tl_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_in_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_in_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_in_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_in_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_in_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_in_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_in_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_tl_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_tl_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_tl_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_tl_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_tl_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_tl_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_tl_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_in_d_bits_corrupt	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire        _widget_auto_anon_out_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [2:0]  _widget_auto_anon_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [2:0]  _widget_auto_anon_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [2:0]  _widget_auto_anon_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [3:0]  _widget_auto_anon_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [29:0] _widget_auto_anon_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire        _widget_auto_anon_out_a_bits_user_amba_prot_bufferable;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire        _widget_auto_anon_out_a_bits_user_amba_prot_modifiable;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire        _widget_auto_anon_out_a_bits_user_amba_prot_readalloc;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire        _widget_auto_anon_out_a_bits_user_amba_prot_writealloc;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire        _widget_auto_anon_out_a_bits_user_amba_prot_privileged;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire        _widget_auto_anon_out_a_bits_user_amba_prot_secure;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire        _widget_auto_anon_out_a_bits_user_amba_prot_fetch;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [3:0]  _widget_auto_anon_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [31:0] _widget_auto_anon_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire        _widget_auto_anon_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire        _widget_auto_anon_out_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire        _fragmenter_auto_anon_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [2:0]  _fragmenter_auto_anon_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [1:0]  _fragmenter_auto_anon_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [2:0]  _fragmenter_auto_anon_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [3:0]  _fragmenter_auto_anon_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [31:0] _fragmenter_auto_anon_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [2:0]  _fragmenter_auto_anon_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [2:0]  _fragmenter_auto_anon_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [1:0]  _fragmenter_auto_anon_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [8:0]  _fragmenter_auto_anon_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [29:0] _fragmenter_auto_anon_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_a_bits_user_amba_prot_bufferable;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_a_bits_user_amba_prot_modifiable;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_a_bits_user_amba_prot_readalloc;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_a_bits_user_amba_prot_writealloc;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_a_bits_user_amba_prot_privileged;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_a_bits_user_amba_prot_secure;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_a_bits_user_amba_prot_fetch;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [3:0]  _fragmenter_auto_anon_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [31:0] _fragmenter_auto_anon_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _tl2apb_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  wire        _tl2apb_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  wire [2:0]  _tl2apb_auto_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  wire [1:0]  _tl2apb_auto_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  wire [1:0]  _tl2apb_auto_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  wire [8:0]  _tl2apb_auto_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  wire        _tl2apb_auto_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  wire        _tl2apb_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  wire [31:0] _tl2apb_auto_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  wire        _tl2apb_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  TLToAPB tl2apb (	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
    .clock                                    (clock),
    .reset                                    (reset),
    .auto_in_a_ready                          (_tl2apb_auto_in_a_ready),
    .auto_in_a_valid                          (_fragmenter_auto_anon_out_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_opcode                    (_fragmenter_auto_anon_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_param                     (_fragmenter_auto_anon_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_size                      (_fragmenter_auto_anon_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_source                    (_fragmenter_auto_anon_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_address                   (_fragmenter_auto_anon_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_user_amba_prot_bufferable (_fragmenter_auto_anon_out_a_bits_user_amba_prot_bufferable),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_user_amba_prot_modifiable (_fragmenter_auto_anon_out_a_bits_user_amba_prot_modifiable),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_user_amba_prot_readalloc  (_fragmenter_auto_anon_out_a_bits_user_amba_prot_readalloc),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_user_amba_prot_writealloc (_fragmenter_auto_anon_out_a_bits_user_amba_prot_writealloc),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_user_amba_prot_privileged (_fragmenter_auto_anon_out_a_bits_user_amba_prot_privileged),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_user_amba_prot_secure     (_fragmenter_auto_anon_out_a_bits_user_amba_prot_secure),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_user_amba_prot_fetch      (_fragmenter_auto_anon_out_a_bits_user_amba_prot_fetch),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_mask                      (_fragmenter_auto_anon_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_data                      (_fragmenter_auto_anon_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_corrupt                   (_fragmenter_auto_anon_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_d_ready                          (_fragmenter_auto_anon_out_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_d_valid                          (_tl2apb_auto_in_d_valid),
    .auto_in_d_bits_opcode                    (_tl2apb_auto_in_d_bits_opcode),
    .auto_in_d_bits_param                     (_tl2apb_auto_in_d_bits_param),
    .auto_in_d_bits_size                      (_tl2apb_auto_in_d_bits_size),
    .auto_in_d_bits_source                    (_tl2apb_auto_in_d_bits_source),
    .auto_in_d_bits_sink                      (_tl2apb_auto_in_d_bits_sink),
    .auto_in_d_bits_denied                    (_tl2apb_auto_in_d_bits_denied),
    .auto_in_d_bits_data                      (_tl2apb_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt                   (_tl2apb_auto_in_d_bits_corrupt),
    .auto_out_psel                            (auto_tl2apb_out_psel),
    .auto_out_penable                         (auto_tl2apb_out_penable),
    .auto_out_pwrite                          (auto_tl2apb_out_pwrite),
    .auto_out_paddr                           (auto_tl2apb_out_paddr),
    .auto_out_pwdata                          (auto_tl2apb_out_pwdata),
    .auto_out_pstrb                           (auto_tl2apb_out_pstrb),
    .auto_out_pready                          (auto_tl2apb_out_pready),
    .auto_out_prdata                          (auto_tl2apb_out_prdata)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  TLFragmenter_1 fragmenter (	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .clock                                          (clock),
    .reset                                          (reset),
    .auto_anon_in_a_ready                           (_fragmenter_auto_anon_in_a_ready),
    .auto_anon_in_a_valid                           (_widget_auto_anon_out_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_opcode                     (_widget_auto_anon_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_param                      (_widget_auto_anon_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_size                       (_widget_auto_anon_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_source                     (_widget_auto_anon_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_address                    (_widget_auto_anon_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_user_amba_prot_bufferable  (_widget_auto_anon_out_a_bits_user_amba_prot_bufferable),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_user_amba_prot_modifiable  (_widget_auto_anon_out_a_bits_user_amba_prot_modifiable),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_user_amba_prot_readalloc   (_widget_auto_anon_out_a_bits_user_amba_prot_readalloc),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_user_amba_prot_writealloc  (_widget_auto_anon_out_a_bits_user_amba_prot_writealloc),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_user_amba_prot_privileged  (_widget_auto_anon_out_a_bits_user_amba_prot_privileged),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_user_amba_prot_secure      (_widget_auto_anon_out_a_bits_user_amba_prot_secure),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_user_amba_prot_fetch       (_widget_auto_anon_out_a_bits_user_amba_prot_fetch),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_mask                       (_widget_auto_anon_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_data                       (_widget_auto_anon_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_a_bits_corrupt                    (_widget_auto_anon_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_d_ready                           (_widget_auto_anon_out_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_anon_in_d_valid                           (_fragmenter_auto_anon_in_d_valid),
    .auto_anon_in_d_bits_opcode                     (_fragmenter_auto_anon_in_d_bits_opcode),
    .auto_anon_in_d_bits_param                      (_fragmenter_auto_anon_in_d_bits_param),
    .auto_anon_in_d_bits_size                       (_fragmenter_auto_anon_in_d_bits_size),
    .auto_anon_in_d_bits_source                     (_fragmenter_auto_anon_in_d_bits_source),
    .auto_anon_in_d_bits_sink                       (_fragmenter_auto_anon_in_d_bits_sink),
    .auto_anon_in_d_bits_denied                     (_fragmenter_auto_anon_in_d_bits_denied),
    .auto_anon_in_d_bits_data                       (_fragmenter_auto_anon_in_d_bits_data),
    .auto_anon_in_d_bits_corrupt                    (_fragmenter_auto_anon_in_d_bits_corrupt),
    .auto_anon_out_a_ready                          (_tl2apb_auto_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
    .auto_anon_out_a_valid                          (_fragmenter_auto_anon_out_a_valid),
    .auto_anon_out_a_bits_opcode                    (_fragmenter_auto_anon_out_a_bits_opcode),
    .auto_anon_out_a_bits_param                     (_fragmenter_auto_anon_out_a_bits_param),
    .auto_anon_out_a_bits_size                      (_fragmenter_auto_anon_out_a_bits_size),
    .auto_anon_out_a_bits_source                    (_fragmenter_auto_anon_out_a_bits_source),
    .auto_anon_out_a_bits_address                   (_fragmenter_auto_anon_out_a_bits_address),
    .auto_anon_out_a_bits_user_amba_prot_bufferable (_fragmenter_auto_anon_out_a_bits_user_amba_prot_bufferable),
    .auto_anon_out_a_bits_user_amba_prot_modifiable (_fragmenter_auto_anon_out_a_bits_user_amba_prot_modifiable),
    .auto_anon_out_a_bits_user_amba_prot_readalloc  (_fragmenter_auto_anon_out_a_bits_user_amba_prot_readalloc),
    .auto_anon_out_a_bits_user_amba_prot_writealloc (_fragmenter_auto_anon_out_a_bits_user_amba_prot_writealloc),
    .auto_anon_out_a_bits_user_amba_prot_privileged (_fragmenter_auto_anon_out_a_bits_user_amba_prot_privileged),
    .auto_anon_out_a_bits_user_amba_prot_secure     (_fragmenter_auto_anon_out_a_bits_user_amba_prot_secure),
    .auto_anon_out_a_bits_user_amba_prot_fetch      (_fragmenter_auto_anon_out_a_bits_user_amba_prot_fetch),
    .auto_anon_out_a_bits_mask                      (_fragmenter_auto_anon_out_a_bits_mask),
    .auto_anon_out_a_bits_data                      (_fragmenter_auto_anon_out_a_bits_data),
    .auto_anon_out_a_bits_corrupt                   (_fragmenter_auto_anon_out_a_bits_corrupt),
    .auto_anon_out_d_ready                          (_fragmenter_auto_anon_out_d_ready),
    .auto_anon_out_d_valid                          (_tl2apb_auto_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
    .auto_anon_out_d_bits_opcode                    (_tl2apb_auto_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
    .auto_anon_out_d_bits_param                     (_tl2apb_auto_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
    .auto_anon_out_d_bits_size                      (_tl2apb_auto_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
    .auto_anon_out_d_bits_source                    (_tl2apb_auto_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
    .auto_anon_out_d_bits_sink                      (_tl2apb_auto_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
    .auto_anon_out_d_bits_denied                    (_tl2apb_auto_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
    .auto_anon_out_d_bits_data                      (_tl2apb_auto_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
    .auto_anon_out_d_bits_corrupt                   (_tl2apb_auto_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAPB.scala:134:28]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  TLWidthWidget8_4 widget (	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .clock                                          (clock),
    .reset                                          (reset),
    .auto_anon_in_a_ready                           (auto_tl_in_a_ready),
    .auto_anon_in_a_valid                           (auto_tl_in_a_valid),
    .auto_anon_in_a_bits_opcode                     (auto_tl_in_a_bits_opcode),
    .auto_anon_in_a_bits_param                      (auto_tl_in_a_bits_param),
    .auto_anon_in_a_bits_size                       (auto_tl_in_a_bits_size),
    .auto_anon_in_a_bits_source                     (auto_tl_in_a_bits_source),
    .auto_anon_in_a_bits_address                    (auto_tl_in_a_bits_address),
    .auto_anon_in_a_bits_user_amba_prot_bufferable  (auto_tl_in_a_bits_user_amba_prot_bufferable),
    .auto_anon_in_a_bits_user_amba_prot_modifiable  (auto_tl_in_a_bits_user_amba_prot_modifiable),
    .auto_anon_in_a_bits_user_amba_prot_readalloc   (auto_tl_in_a_bits_user_amba_prot_readalloc),
    .auto_anon_in_a_bits_user_amba_prot_writealloc  (auto_tl_in_a_bits_user_amba_prot_writealloc),
    .auto_anon_in_a_bits_user_amba_prot_privileged  (auto_tl_in_a_bits_user_amba_prot_privileged),
    .auto_anon_in_a_bits_user_amba_prot_secure      (auto_tl_in_a_bits_user_amba_prot_secure),
    .auto_anon_in_a_bits_user_amba_prot_fetch       (auto_tl_in_a_bits_user_amba_prot_fetch),
    .auto_anon_in_a_bits_mask                       (auto_tl_in_a_bits_mask),
    .auto_anon_in_a_bits_data                       (auto_tl_in_a_bits_data),
    .auto_anon_in_a_bits_corrupt                    (auto_tl_in_a_bits_corrupt),
    .auto_anon_in_d_ready                           (auto_tl_in_d_ready),
    .auto_anon_in_d_valid                           (auto_tl_in_d_valid),
    .auto_anon_in_d_bits_opcode                     (auto_tl_in_d_bits_opcode),
    .auto_anon_in_d_bits_param                      (auto_tl_in_d_bits_param),
    .auto_anon_in_d_bits_size                       (auto_tl_in_d_bits_size),
    .auto_anon_in_d_bits_source                     (auto_tl_in_d_bits_source),
    .auto_anon_in_d_bits_sink                       (auto_tl_in_d_bits_sink),
    .auto_anon_in_d_bits_denied                     (auto_tl_in_d_bits_denied),
    .auto_anon_in_d_bits_data                       (auto_tl_in_d_bits_data),
    .auto_anon_in_d_bits_corrupt                    (auto_tl_in_d_bits_corrupt),
    .auto_anon_out_a_ready                          (_fragmenter_auto_anon_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_anon_out_a_valid                          (_widget_auto_anon_out_a_valid),
    .auto_anon_out_a_bits_opcode                    (_widget_auto_anon_out_a_bits_opcode),
    .auto_anon_out_a_bits_param                     (_widget_auto_anon_out_a_bits_param),
    .auto_anon_out_a_bits_size                      (_widget_auto_anon_out_a_bits_size),
    .auto_anon_out_a_bits_source                    (_widget_auto_anon_out_a_bits_source),
    .auto_anon_out_a_bits_address                   (_widget_auto_anon_out_a_bits_address),
    .auto_anon_out_a_bits_user_amba_prot_bufferable (_widget_auto_anon_out_a_bits_user_amba_prot_bufferable),
    .auto_anon_out_a_bits_user_amba_prot_modifiable (_widget_auto_anon_out_a_bits_user_amba_prot_modifiable),
    .auto_anon_out_a_bits_user_amba_prot_readalloc  (_widget_auto_anon_out_a_bits_user_amba_prot_readalloc),
    .auto_anon_out_a_bits_user_amba_prot_writealloc (_widget_auto_anon_out_a_bits_user_amba_prot_writealloc),
    .auto_anon_out_a_bits_user_amba_prot_privileged (_widget_auto_anon_out_a_bits_user_amba_prot_privileged),
    .auto_anon_out_a_bits_user_amba_prot_secure     (_widget_auto_anon_out_a_bits_user_amba_prot_secure),
    .auto_anon_out_a_bits_user_amba_prot_fetch      (_widget_auto_anon_out_a_bits_user_amba_prot_fetch),
    .auto_anon_out_a_bits_mask                      (_widget_auto_anon_out_a_bits_mask),
    .auto_anon_out_a_bits_data                      (_widget_auto_anon_out_a_bits_data),
    .auto_anon_out_a_bits_corrupt                   (_widget_auto_anon_out_a_bits_corrupt),
    .auto_anon_out_d_ready                          (_widget_auto_anon_out_d_ready),
    .auto_anon_out_d_valid                          (_fragmenter_auto_anon_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_anon_out_d_bits_opcode                    (_fragmenter_auto_anon_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_anon_out_d_bits_param                     (_fragmenter_auto_anon_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_anon_out_d_bits_size                      (_fragmenter_auto_anon_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_anon_out_d_bits_source                    (_fragmenter_auto_anon_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_anon_out_d_bits_sink                      (_fragmenter_auto_anon_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_anon_out_d_bits_denied                    (_fragmenter_auto_anon_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_anon_out_d_bits_data                      (_fragmenter_auto_anon_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_anon_out_d_bits_corrupt                   (_fragmenter_auto_anon_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
endmodule

