# SYSCLK 200MHz
set_property -dict {PACKAGE_PIN D24 IOSTANDARD DIFF_SSTL12} [get_ports sys_clock_p]
set_property -dict {PACKAGE_PIN C24 IOSTANDARD DIFF_SSTL12} [get_ports sys_clock_n]

# CPU reset button
set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS33} [get_ports reset_0]


#DDR4
set_property PACKAGE_PIN E23 [get_ports ddr_c0_ddr4_cs_n]
set_property PACKAGE_PIN D23 [get_ports ddr_c0_ddr4_ck_t]
set_property PACKAGE_PIN C23 [get_ports ddr_c0_ddr4_ck_c]
set_property PACKAGE_PIN C21 [get_ports ddr_c0_ddr4_cke]
set_property PACKAGE_PIN B29 [get_ports ddr_c0_ddr4_reset_n]
set_property PACKAGE_PIN A25 [get_ports ddr_c0_ddr4_act_n]
set_property PACKAGE_PIN F25 [get_ports {ddr_c0_ddr4_ba[1]}]
set_property PACKAGE_PIN E20 [get_ports {ddr_c0_ddr4_ba[0]}]
set_property PACKAGE_PIN D20 [get_ports ddr_c0_ddr4_odt]
set_property PACKAGE_PIN B21 [get_ports ddr_c0_ddr4_bg]
set_property PACKAGE_PIN C22 [get_ports {ddr_c0_ddr4_adr[0]}]
set_property PACKAGE_PIN G24 [get_ports {ddr_c0_ddr4_adr[1]}]
set_property PACKAGE_PIN D29 [get_ports {ddr_c0_ddr4_adr[2]}]
set_property PACKAGE_PIN A28 [get_ports {ddr_c0_ddr4_adr[3]}]
set_property PACKAGE_PIN E22 [get_ports {ddr_c0_ddr4_adr[4]}]
set_property PACKAGE_PIN A29 [get_ports {ddr_c0_ddr4_adr[5]}]
set_property PACKAGE_PIN A20 [get_ports {ddr_c0_ddr4_adr[6]}]
set_property PACKAGE_PIN A27 [get_ports {ddr_c0_ddr4_adr[7]}]
set_property PACKAGE_PIN F23 [get_ports {ddr_c0_ddr4_adr[8]}]
set_property PACKAGE_PIN D28 [get_ports {ddr_c0_ddr4_adr[9]}]
set_property PACKAGE_PIN B20 [get_ports {ddr_c0_ddr4_adr[10]}]
set_property PACKAGE_PIN D21 [get_ports {ddr_c0_ddr4_adr[11]}]
set_property PACKAGE_PIN E26 [get_ports {ddr_c0_ddr4_adr[12]}]
set_property PACKAGE_PIN E28 [get_ports {ddr_c0_ddr4_adr[13]}]
set_property PACKAGE_PIN E21 [get_ports {ddr_c0_ddr4_adr[14]}]
set_property PACKAGE_PIN F24 [get_ports {ddr_c0_ddr4_adr[15]}]
set_property PACKAGE_PIN G20 [get_ports {ddr_c0_ddr4_adr[16]}]
set_property PACKAGE_PIN B10 [get_ports {ddr_c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN A10 [get_ports {ddr_c0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN K10 [get_ports {ddr_c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN J10 [get_ports {ddr_c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN L13 [get_ports {ddr_c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN K13 [get_ports {ddr_c0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN F13 [get_ports {ddr_c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN E13 [get_ports {ddr_c0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN C19 [get_ports {ddr_c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN B19 [get_ports {ddr_c0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN D19 [get_ports {ddr_c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN D18 [get_ports {ddr_c0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN G19 [get_ports {ddr_c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN F19 [get_ports {ddr_c0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN J19 [get_ports {ddr_c0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN J18 [get_ports {ddr_c0_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN F8 [get_ports {ddr_c0_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN L8 [get_ports {ddr_c0_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN H11 [get_ports {ddr_c0_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN E11 [get_ports {ddr_c0_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN B14 [get_ports {ddr_c0_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN D14 [get_ports {ddr_c0_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN G17 [get_ports {ddr_c0_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN J15 [get_ports {ddr_c0_ddr4_dm_dbi_n[7]}]
set_property PACKAGE_PIN D10 [get_ports {ddr_c0_ddr4_dq[0]}]
set_property PACKAGE_PIN C8 [get_ports {ddr_c0_ddr4_dq[1]}]
set_property PACKAGE_PIN D9 [get_ports {ddr_c0_ddr4_dq[2]}]
set_property PACKAGE_PIN C9 [get_ports {ddr_c0_ddr4_dq[3]}]
set_property PACKAGE_PIN E10 [get_ports {ddr_c0_ddr4_dq[4]}]
set_property PACKAGE_PIN D8 [get_ports {ddr_c0_ddr4_dq[5]}]
set_property PACKAGE_PIN A9 [get_ports {ddr_c0_ddr4_dq[6]}]
set_property PACKAGE_PIN B9 [get_ports {ddr_c0_ddr4_dq[7]}]
set_property PACKAGE_PIN G10 [get_ports {ddr_c0_ddr4_dq[8]}]
set_property PACKAGE_PIN J8 [get_ports {ddr_c0_ddr4_dq[9]}]
set_property PACKAGE_PIN F9 [get_ports {ddr_c0_ddr4_dq[10]}]
set_property PACKAGE_PIN H8 [get_ports {ddr_c0_ddr4_dq[11]}]
set_property PACKAGE_PIN F10 [get_ports {ddr_c0_ddr4_dq[12]}]
set_property PACKAGE_PIN J9 [get_ports {ddr_c0_ddr4_dq[13]}]
set_property PACKAGE_PIN G9 [get_ports {ddr_c0_ddr4_dq[14]}]
set_property PACKAGE_PIN H9 [get_ports {ddr_c0_ddr4_dq[15]}]
set_property PACKAGE_PIN H12 [get_ports {ddr_c0_ddr4_dq[16]}]
set_property PACKAGE_PIN K12 [get_ports {ddr_c0_ddr4_dq[17]}]
set_property PACKAGE_PIN G12 [get_ports {ddr_c0_ddr4_dq[18]}]
set_property PACKAGE_PIN K11 [get_ports {ddr_c0_ddr4_dq[19]}]
set_property PACKAGE_PIN H13 [get_ports {ddr_c0_ddr4_dq[20]}]
set_property PACKAGE_PIN L12 [get_ports {ddr_c0_ddr4_dq[21]}]
set_property PACKAGE_PIN J13 [get_ports {ddr_c0_ddr4_dq[22]}]
set_property PACKAGE_PIN J11 [get_ports {ddr_c0_ddr4_dq[23]}]
set_property PACKAGE_PIN A13 [get_ports {ddr_c0_ddr4_dq[24]}]
set_property PACKAGE_PIN C11 [get_ports {ddr_c0_ddr4_dq[25]}]
set_property PACKAGE_PIN C13 [get_ports {ddr_c0_ddr4_dq[26]}]
set_property PACKAGE_PIN B11 [get_ports {ddr_c0_ddr4_dq[27]}]
set_property PACKAGE_PIN D13 [get_ports {ddr_c0_ddr4_dq[28]}]
set_property PACKAGE_PIN C12 [get_ports {ddr_c0_ddr4_dq[29]}]
set_property PACKAGE_PIN B12 [get_ports {ddr_c0_ddr4_dq[30]}]
set_property PACKAGE_PIN A12 [get_ports {ddr_c0_ddr4_dq[31]}]
set_property PACKAGE_PIN A19 [get_ports {ddr_c0_ddr4_dq[32]}]
set_property PACKAGE_PIN B16 [get_ports {ddr_c0_ddr4_dq[33]}]
set_property PACKAGE_PIN C18 [get_ports {ddr_c0_ddr4_dq[34]}]
set_property PACKAGE_PIN B17 [get_ports {ddr_c0_ddr4_dq[35]}]
set_property PACKAGE_PIN A18 [get_ports {ddr_c0_ddr4_dq[36]}]
set_property PACKAGE_PIN B15 [get_ports {ddr_c0_ddr4_dq[37]}]
set_property PACKAGE_PIN C17 [get_ports {ddr_c0_ddr4_dq[38]}]
set_property PACKAGE_PIN A15 [get_ports {ddr_c0_ddr4_dq[39]}]
set_property PACKAGE_PIN E18 [get_ports {ddr_c0_ddr4_dq[40]}]
set_property PACKAGE_PIN E15 [get_ports {ddr_c0_ddr4_dq[41]}]
set_property PACKAGE_PIN E16 [get_ports {ddr_c0_ddr4_dq[42]}]
set_property PACKAGE_PIN F15 [get_ports {ddr_c0_ddr4_dq[43]}]
set_property PACKAGE_PIN E17 [get_ports {ddr_c0_ddr4_dq[44]}]
set_property PACKAGE_PIN D15 [get_ports {ddr_c0_ddr4_dq[45]}]
set_property PACKAGE_PIN D16 [get_ports {ddr_c0_ddr4_dq[46]}]
set_property PACKAGE_PIN F14 [get_ports {ddr_c0_ddr4_dq[47]}]
set_property PACKAGE_PIN H18 [get_ports {ddr_c0_ddr4_dq[48]}]
set_property PACKAGE_PIN H16 [get_ports {ddr_c0_ddr4_dq[49]}]
set_property PACKAGE_PIN H17 [get_ports {ddr_c0_ddr4_dq[50]}]
set_property PACKAGE_PIN G15 [get_ports {ddr_c0_ddr4_dq[51]}]
set_property PACKAGE_PIN H19 [get_ports {ddr_c0_ddr4_dq[52]}]
set_property PACKAGE_PIN F17 [get_ports {ddr_c0_ddr4_dq[53]}]
set_property PACKAGE_PIN F18 [get_ports {ddr_c0_ddr4_dq[54]}]
set_property PACKAGE_PIN G14 [get_ports {ddr_c0_ddr4_dq[55]}]
set_property PACKAGE_PIN L19 [get_ports {ddr_c0_ddr4_dq[56]}]
set_property PACKAGE_PIN K15 [get_ports {ddr_c0_ddr4_dq[57]}]
set_property PACKAGE_PIN L18 [get_ports {ddr_c0_ddr4_dq[58]}]
set_property PACKAGE_PIN K17 [get_ports {ddr_c0_ddr4_dq[59]}]
set_property PACKAGE_PIN K18 [get_ports {ddr_c0_ddr4_dq[60]}]
set_property PACKAGE_PIN J16 [get_ports {ddr_c0_ddr4_dq[61]}]
set_property PACKAGE_PIN K16 [get_ports {ddr_c0_ddr4_dq[62]}]
set_property PACKAGE_PIN L15 [get_ports {ddr_c0_ddr4_dq[63]}]
set_property INTERNAL_VREF 0.6 [get_iobanks 64]


# SDIO
#set_property -dict {PACKAGE_PIN U26 IOSTANDARD LVCMOS18 IOB TRUE} [get_ports sdio_spi_clk]
#set_property -dict {PACKAGE_PIN U27 IOSTANDARD LVCMOS18} [get_ports sdio_spi_cs]
#set_property PULLUP true [get_ports sdio_spi_cs]
#set_property IOB TRUE [get_cells -of_objects [all_fanin -flat -startpoints_only [get_ports sdio_spi_cs]]]

#set_property -dict {PACKAGE_PIN Y27 IOSTANDARD LVCMOS18} [get_ports sdio_spi_dat_0]
#set_property PULLUP true [get_ports sdio_spi_dat_0]
#set_property -dict {PACKAGE_PIN Y26 IOSTANDARD LVCMOS18} [get_ports sdio_spi_dat_1]
#set_property PULLUP true [get_ports sdio_spi_dat_1]
#set_property -dict {PACKAGE_PIN V28 IOSTANDARD LVCMOS18} [get_ports sdio_spi_dat_2]
#set_property PULLUP true [get_ports sdio_spi_dat_2]
#set_property -dict {PACKAGE_PIN V27 IOSTANDARD LVCMOS18} [get_ports sdio_spi_dat_3]
#set_property PULLUP true [get_ports sdio_spi_dat_3]

# UART
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS33} [get_ports uart_txd]
set_property -dict {PACKAGE_PIN N23 IOSTANDARD LVCMOS33} [get_ports uart_rxd]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets jtag_jtag_TCK]
set_property PULLUP true [get_ports jtag_jtag_TCK]
set_property PULLUP true [get_ports jtag_jtag_TMS]
set_property PULLUP true [get_ports jtag_jtag_TDI]
set_property PULLUP true [get_ports jtag_jtag_TDO]
set_property PULLUP true [get_ports jtag_srst_n]

set_property -dict {PACKAGE_PIN AJ13 IOSTANDARD LVCMOS33} [get_ports jtag_jtag_TDI]
set_property -dict {PACKAGE_PIN AH12 IOSTANDARD LVCMOS33} [get_ports jtag_jtag_TCK]
set_property -dict {PACKAGE_PIN AG12 IOSTANDARD LVCMOS33} [get_ports jtag_jtag_TMS]
set_property -dict {PACKAGE_PIN AE13 IOSTANDARD LVCMOS33} [get_ports jtag_jtag_TDO]
set_property -dict {PACKAGE_PIN AF13 IOSTANDARD LVCMOS33} [get_ports jtag_srst_n]

