PRJ_SDK_DIR := /home/jdeng/work/cm3_soc_sw/project/firmware_sdk
PRJ_FW_DIR  := /home/jdeng/work/cm3_soc_sw/firmware
PRJ_LIB_DIR := /home/jdeng/work/cm3_soc_sw/library
PRJ_DRV_DIR := ${PRJ_LIB_DIR}/drivers
SDK_TARGET := bootloader
SDK_DEFINE := -D__NO_SYSTEM_INIT -DUART_DRIVER -DUART_EX_DRIVER -DCOMMON_DRIVER

SDK_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}
BUILD_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}/build-fw
OUTPUT_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}/output
FW_PATH := ${PRJ_FW_DIR}/${SDK_TARGET}
FW_INC_PATH := -I ${PRJ_FW_DIR}/${SDK_TARGET}/boot/inc
CPU_INC_PATH := -I ${PRJ_LIB_DIR}/cmsis/CMSIS/Include -I ${PRJ_LIB_DIR}/cmsis/Device/ARM/CM3DS/Include
UART_INC_PATH := -I ${PRJ_DRV_DIR} -I ${PRJ_DRV_DIR}/common/inc -I ${PRJ_DRV_DIR}/uart/inc
CALIPTRA1X_INC_PATH := -I ${PRJ_DRV_DIR} -I ${PRJ_DRV_DIR}/common/inc -I ${PRJ_DRV_DIR}/caliptra1x/inc
INC_PATH := ${FW_INC_PATH} ${CPU_INC_PATH} ${UART_INC_PATH} ${GPIO_INC_PATH} ${CALIPTRA1X_INC_PATH}

LDSCRIPT := ${FW_PATH}/firmware_itcm.ld
STARTUP_S := ${PRJ_LIB_DIR}/cmsis/Device/ARM/CM3DS/Source/GCC/startup_CM3DS_fw.s

CFLAG := -std=c99 -DPRJ=${SDK_TARGET} -D__GNUC__=9 -Og -Wall -Wextra -fdata-sections -ffunction-sections
ARCH_FLAG := -mthumb -mthumb-interwork -mcpu=cortex-m3
LDFLAG := -Wl,-gc-sections -Wl,-Map=${SDK_TARGET}-fw.map,--cref -specs=nano.specs -specs=nosys.specs
FLAG := ${CFLAG} ${ARCH_FLAG}

SHELL := /bin/bash

all: prepare compile link build dump

prepare:
	-mkdir ${SDK_PATH}
	-mkdir ${BUILD_PATH}
	-mkdir ${OUTPUT_PATH}

compile:
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/common/src/drv_common.c -o ${BUILD_PATH}/drv_common.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/uart/src/drv_uart.c -o ${BUILD_PATH}/drv_uart.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/uart/src/drv_uart_ex.c -o ${BUILD_PATH}/drv_uart_ex.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/caliptra1x/src/drv_caliptra1x.c -o ${BUILD_PATH}/drv_caliptra1x.c.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/caliptra1x/src/mailbox.c -o ${BUILD_PATH}/mailbox.c.o

	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/boot/src/main-fw.c -o ${BUILD_PATH}/main-fw.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/boot/src/interrupt.c -o ${BUILD_PATH}/interrupt.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${STARTUP_S} -o ${BUILD_PATH}/startup_CM3DS_fw.o

link:
	cd ${BUILD_PATH} && arm-none-eabi-gcc -T ${LDSCRIPT} ${ARCH_FLAG} *.o -o ${SDK_TARGET}-fw.elf ${LDFLAG}

build:
	mv ${BUILD_PATH}/${SDK_TARGET}-fw.elf ${OUTPUT_PATH}
	mv ${BUILD_PATH}/${SDK_TARGET}-fw.map ${OUTPUT_PATH}
	cd ${OUTPUT_PATH} && arm-none-eabi-objcopy -O binary -S ${SDK_TARGET}-fw.elf ${SDK_TARGET}-fw.bin
	cd ${OUTPUT_PATH} && BIN_SIZE=$$(stat -c%s ${SDK_TARGET}-fw.bin) && PAD_SIZE=$$(( ( ($$BIN_SIZE + 511) / 512 ) * 512 )) && dd if=/dev/zero bs=1 count=$$(( $$PAD_SIZE - $$BIN_SIZE )) >> ${SDK_TARGET}-fw.bin
	cd ${OUTPUT_PATH} && arm-none-eabi-objcopy -O ihex -S ${SDK_TARGET}-fw.elf ${SDK_TARGET}-fw.hex
	
dump:
	cd ${OUTPUT_PATH} && arm-none-eabi-objdump -D ${SDK_TARGET}-fw.elf > ${SDK_TARGET}-fw.asm

