#ifndef CLUSTER_BLS_SCALE_TEST_H_
#define CLUSTER_BLS_SCALE_TEST_H_

#ifndef CLUSTER_BLS_SCALE_TEST_ENABLE
#define CLUSTER_BLS_SCALE_TEST_ENABLE 1
#endif

#define CLUSTER_BLS_SCALE_CHILDREN 10U
#define CLUSTER_BLS_SCALE_MAX_GROUPS 1000U
#define CLUSTER_BLS_SCALE_REQUEST_BYTES (40U + 96U * CLUSTER_BLS_SCALE_CHILDREN)
#define CLUSTER_BLS_SCALE_RESPONSE_BYTES 124U

#endif
